
text = input("Enter some text:")
print(text)
print("Enter a number:")
number = input()
print(int(number) + 1)
print("Enter a number:")
number_2 = input()
print(float(number_2) + .5)
# adding floats
print("Enter a number:")
number_3 = input()
print("Enter another number:")
number_4 = input()
sum = float(number_3) + float(number_4)
print("The sum is {}".format(sum))
# multiplying floats
print("Enter a number:")
number_5 = input()
print("Enter another number:")
number_6 = input()
product = float(number_5) * float(number_6)
print("The product is {}". format(product))
# dividing integers
print("Enter a number")
number_7 = input()
print("Enter another number:")
number_8 = input()
result = float(number_7) / float(number_8)
print("The result is {}". format(result))
# entering booleans
print("The sky is blue, True or False")
response = input()
print("You entered:" + response)
print("The opposite value of your value is: False" )